exxcellent/swt2-bsa-frontend

bogenliga/src/app/modules/shared/components/tables/control/table-config-mapper.ts, bogenliga/src/app/modules/shared/components/tables/data-table/data-table.component.ts, bogenliga/src/app/modules/shared/components/tables/types/table-action-type.enum.ts, bogenliga/src/app/modules/vereine/components/vereine/vereine.component.ts, bogenliga/src/app/modules/verwaltung/components/dsb-mitglied/dsb-mitglied-detail/dsb-mitglied-detail.component.html, bogenliga/src/app/modules/verwaltung/components/dsb-mitglied/dsb-mitglied-detail/dsb-mitglied-detail.component.ts, bogenliga/src/app/modules/verwaltung/components/verein/verein-detail/mannschafts-detail/mannschaft-detail.component.html, bogenliga/src/app/modules/verwaltung/components/verein/verein-detail/mannschafts-detail/mannschaft-detail.component.ts, bogenliga/src/app/modules/verwaltung/components/verein/verein-detail/mannschafts-detail/mannschaft-detail.config.ts, bogenliga/src/app/modules/verwaltung/components/verein/verein-detail/mannschafts-detail/schuetzen/schuetzen.component.html, bogenliga/src/app/modules/verwaltung/components/verein/verein-detail/mannschafts-detail/schuetzen/schuetzen.component.ts, bogenliga/src/app/modules/verwaltung/components/verein/verein-detail/mannschafts-detail/schuetzen/schuetzen.config.ts, bogenliga/src/app/modules/verwaltung/components/verein/verein-detail/verein-detail.component.ts, bogenliga/src/app/modules/verwaltung/mapper/lizenz-mapper.ts, bogenliga/src/app/modules/verwaltung/mapper/passe-mapper.ts, bogenliga/src/app/modules/verwaltung/services/dsb-mitglied-data-provider.service.ts, bogenliga/src/app/modules/verwaltung/services/lizenz-data-provider.service.ts, bogenliga/src/app/modules/verwaltung/services/passe-data-provider-sercie.ts, bogenliga/src/app/modules/verwaltung/services/wettkampf-data-provider.service.ts, bogenliga/src/app/modules/verwaltung/types/datatransfer/dsb-mitglied-dto.class.ts, bogenliga/src/app/modules/verwaltung/types/datatransfer/lizenz-dto.class.ts, bogenliga/src/app/modules/verwaltung/types/datatransfer/mannschaftsmitglied-dto.class.ts, bogenliga/src/app/modules/verwaltung/types/datatransfer/passe-dto.class.ts, bogenliga/src/app/modules/verwaltung/types/dsb-mitglied-do.class.ts, bogenliga/src/app/modules/verwaltung/types/lizenz-do.class.ts, bogenliga/src/app/modules/verwaltung/types/passe-do-class.ts, bogenliga/src/app/modules/verwaltung/verwaltung.module.ts, bogenliga/src/app/modules/wettkampf/services/download-provider.service.ts, bogenliga/src/assets/i18n/de.json
=> Scrumicorns

bogenliga/src/app/app.routing.ts, bogenliga/src/app/components/sidebar/sidebar.config.ts, bogenliga/src/app/modules/mannschaft/components/index.ts, bogenliga/src/app/modules/mannschaft/components/mannschaft/mannschaft.component.html, bogenliga/src/app/modules/mannschaft/components/mannschaft/mannschaft.component.ts, bogenliga/src/app/modules/mannschaft/components/mannschaft/mannschaft.config.ts, bogenliga/src/app/modules/mannschaft/components/mannschaft/wettkampergebnis/WettkampfErgebnis.Service.ts, bogenliga/src/app/modules/mannschaft/components/mannschaft/wettkampergebnis/WettkampfErgebnis.ts, bogenliga/src/app/modules/mannschaft/components/mannschaft/wettkampergebnis/tabelle.config.ts, bogenliga/src/app/modules/mannschaft/index.ts, bogenliga/src/app/modules/mannschaft/mannschaft.module.ts, bogenliga/src/app/modules/mannschaft/mannschaft.routing.ts, bogenliga/src/app/modules/vereine/services/match-data-provider.service.ts, bogenliga/src/app/modules/verwaltung/components/region/region-detail/region-detail.component.html, bogenliga/src/app/modules/verwaltung/components/region/region-detail/region-detail.component.ts, bogenliga/src/app/modules/verwaltung/components/region/region-overview/region-overview.component.ts, bogenliga/src/assets/i18n/de.json, bogenliga/src/environments/environment.prod.ts
BSAPP-251 fertig gestellt, BSAPP-145 angefangen.
=> Scrummasters of desaster

bogenliga/src/app/modules/schusszettel/components/tablet-admin/tablet-admin.component.html, bogenliga/src/app/modules/schusszettel/components/tableteingabe/tableteingabe.component.html, bogenliga/src/app/modules/schusszettel/components/tableteingabe/tableteingabe.component.ts
add code documentation to tableteingabe component
=> fix various issues in tableteingabe component

bogenliga/src/app/modules/verwaltung/components/veranstaltung/veranstaltung-detail/wettkampftage/wettkampftage.component.html, bogenliga/src/app/modules/verwaltung/components/veranstaltung/veranstaltung-detail/wettkampftage/wettkampftage.component.ts, bogenliga/src/assets/i18n/de.json
Bugfixing Pflege Wettkampftage
=> Bsapp 453 liga tabelle anzeigen

bogenliga/src/app/components/navbar/components/user-dropdown/user-dropdown.component.ts, bogenliga/src/app/modules/home/components/home/home.component.ts, bogenliga/src/app/modules/shared/redux-store/feature/user/user.actions.ts, bogenliga/src/app/modules/shared/redux-store/feature/user/user.reducer.ts, bogenliga/src/app/modules/shared/services/current-user/current-user.service.ts, bogenliga/src/app/modules/user/services/login-data-provider.service.ts
=> Bsapp 509 travis

bogenliga/package-lock.json, bogenliga/src/app/modules/verwaltung/components/liga/liga-detail/liga-detail.component.ts
The 'liga-detail' page will now redirect to the 'liga-overview' page after successfully creating a new 'liga'.
The error was the wrong use of 'navigateByURL'.
=> Fixed Issue BSAPP-494

bogenliga/src/app/modules/verwaltung/components/benutzer/benutzer-neu/benutzer-neu.component.html, bogenliga/src/assets/i18n/de.json
Changed Password Validity-Check on the client-side (as well as on the server-side). You can now also use special characters like #$^+=!*()@%&? for your password.
The pattern now also correctly validates the length of the password.
=> Fixed Issue BSAPP-488

bogenliga/src/app/modules/wettkampf/components/wettkampf/wettkampf.component.html, bogenliga/src/app/modules/wettkampf/components/wettkampf/wettkampf.component.ts
Bugfix durch Loadingattribut, verhindert dass Tabelle nicht angezeigt wird
=> Bsapp 479 mit subtasks

bogenliga/package-lock.json, bogenliga/src/app/modules/sportjahresplan/components/schusszettel/schusszettel.component.ts, bogenliga/src/assets/i18n/de.json
Felder-Initialisierung korrigiert und Kommentare ergänzt
=> Reperatur schiesszettel

bogenliga/package-lock.json, bogenliga/src/app/modules/sportjahresplan/components/schusszettel/schusszettel.component.ts, bogenliga/src/app/modules/verwaltung/components/verein/verein-detail/mannschafts-detail/mannschaft-detail.component.html, bogenliga/src/app/modules/verwaltung/components/verein/verein-detail/mannschafts-detail/mannschaft-detail.component.ts, bogenliga/src/assets/i18n/de.json
Bugfixes gem. Commit Kommentaren: Anzeige der Schützen in der Bogenkontrollliste, Update/Anzeige der Zuordnung Mannschaft zu Veranstaltung im Dialog "DSB-Mannschaft-Details
=> Reperatur bogenkontrollliste

bogenliga/src/app/modules/verwaltung/components/verwaltung/verwaltung.config.ts
Fixed Bug: BSAPP-498 by commenting out the button/site "Sportjahre" in "Verwaltung" in verwaltung.config.ts
=> Fixed Bug: BSAPP-498

bogenliga/src/app/modules/sportjahresplan/components/schusszettel/tabindex.directive.ts
BSAPP 504 fixed moves now like zick zack
=> Taborder moves now like Zick Zack Pfeil 1 Pfeil 2 then jumps down

bogenliga/src/app/modules/verwaltung/components/verein/verein-detail/mannschafts-detail/schuetzen/schuetzen.component.html, bogenliga/src/app/modules/verwaltung/components/verein/verein-detail/mannschafts-detail/schuetzen/schuetzen.component.ts
Es werden nur noch Mitglieder des eigenen Vereines angezeigt , somit können auch nur noch diese Hinzugefügt werden. Suchfeld für Verein wurde entfernt
=> BSAP-624 Manschafts Mitglieder aus anderen vereinen

bogenliga/src/app/modules/sportjahresplan/components/schusszettel/schusszettel.component.html, bogenliga/src/app/modules/sportjahresplan/components/schusszettel/schusszettel.component.scss
=> ~schusszettel.component.html, schusszettel.component.scss

bogenliga/src/app/modules/home/components/home/home.component.html, bogenliga/src/app/modules/home/components/home/home.component.ts, bogenliga/src/app/modules/home/components/home/home.config.ts, bogenliga/src/app/modules/home/components/home/wettkampf/wettkampf.config.ts, bogenliga/src/app/modules/vereine/components/vereine/vereine.component.html, bogenliga/src/app/modules/vereine/components/vereine/vereine.component.ts, bogenliga/src/app/modules/vereine/components/vereine/vereine.config.ts, bogenliga/src/app/modules/vereine/types/vereinsTabelle-do.class.ts
UserStory BSAPP-534.
Home.component.html   
Einzufügen des download events
home.component.ts 
Einfügen der Download Funktion
wettkampf.config.ts  
Hinzufügen der Download Aktion in die Tabelle.
vereine.component.html   
Hinzufügen des download events
vereinsTabelle-do.class.ts 
Erweiterung des DO um WettkampfOrt.
vereine.component.ts 
Einfügen der Verlinkung auf GoogleMaps mit Wettkampfort(Adresse). Erweitern der Vereinstabelle mit Ortsangabe des Wettkampftages.
vereine.config.ts  
Erweitern der Vereinen_Table_Config um Download Aktion und Ortsangabe
=> BSAPP-534 Veranstalltungadressen und Google maps link

bogenliga/src/app/modules/shared/components/tables/data-table/data-table.component.ts, bogenliga/src/app/modules/shared/components/tables/types/table-config.interface.ts, bogenliga/src/app/modules/sportjahresplan/components/sportjahresplan/sportjahresplan.config.ts
Die TableActionType.MAP wurde letzen merge mit TableActionType.DOWNLOADRUECKENNUMMER ersetzt, nachreichung der funktionalität von MAP in data-Table.component.ts
=> Bsapp 534 Map Funktion

bogenliga/src/app/modules/regionen/components/regionen/regionen.component.html, bogenliga/src/app/modules/regionen/components/regionen/regionen.component.ts
Die Variable "PLACEHOLDER_VAR" wurde durch einen eindeutigeren Text mit Bezug zum Dialog ersetzt.
=> ~ "PLACEHOLDER_VAR" umbenannt zu "NO_REGION_SELECTED"

bogenliga/src/app/modules/shared/services/current-user/types/user-permission.enum.ts, bogenliga/src/app/modules/verwaltung/components/benutzer/benutzer-overview/benutzer-overview-active.config.ts, bogenliga/src/app/modules/verwaltung/components/dsb-mitglied/dsb-mitglied-overview/dsb-mitglied-overview.config.ts, bogenliga/src/app/modules/verwaltung/components/liga/liga-overview/liga-overview.config.ts, bogenliga/src/app/modules/verwaltung/components/region/region-overview/region-overview.config.ts, bogenliga/src/app/modules/verwaltung/components/veranstaltung/veranstaltung-overview/veranstaltung-overview.config.ts, bogenliga/src/app/modules/verwaltung/components/verein/verein-overview/verein-overview.config.ts, bogenliga/src/app/modules/verwaltung/components/wettkampfklasse/wettkampfklasse-overview/wettkampfklasse-overview.config.ts, bogenliga/src/app/modules/verwaltung/guards/benutzer-neu.guard.ts
Die Create Permissons sind verloren gegangen.
Ich hab diese wieder hinzugefügt
=> readded create permissons

bogenliga/src/app/modules/ligatabelle/components/ligatabelle/ligatabelle.component.html
- Link funktionalität von Liegen-Auswahl und Liga-Tabelle entfernt.
=> - ligatabelle.component.html

bogenliga/src/app/modules/vereine/components/vereine/vereine.component.ts, bogenliga/src/app/modules/verwaltung/services/verein-data-provider.service.ts
Habe den findFirst wieder entfernt und andere Überbleibsel Auskomentierten Code entfernt.
Achtung! es gibt hierzu auch einen request im Backend
=> Aufräumen von nicht mehr benötigten funktionen.

bogenliga/src/app/modules/verwaltung/components/verein/verein-detail/mannschafts-detail/mannschaft-detail.component.html, bogenliga/src/app/modules/verwaltung/components/verein/verein-detail/mannschafts-detail/mannschaft-detail.component.ts
Bsapp 656:
in mannschaft-detail.component.ts :
Methode: existsMannschaftsNummer hinzugefügt
und diese in Methode: onSave verwendet um zu checken ob Mannschaft mit der Nummer schon existiert
BSAPP-684:
in mannschaft-detail.component.html
Button "Löschen" auskommentiert da dieser nicht funktionierte und die Delete-Funktion lahm legte.
=> Bsapp 656 und BSAPP-684

bogenliga/src/app/modules/vereine/components/vereine/vereine.component.ts
(Manchmal laden Wettkämpfe der Mannschaften nicht, wenn man von Regionen zu Vereine navigiert)
Aufbau von const mannschaftsName verändert in handleFindMannschaftenSucces() bei vereine.component.ts, Zeile 184-198
=> Fixed: BSAPP-622 Solution Lounge

bogenliga/src/app/modules/shared/components/buttons/download-button/download-button.component.ts
but cause of merge mistak where those changes deleted.
=> The same changes from the commit "daee4d2"

bogenliga/src/app/modules/verwaltung/components/benutzer/benutzer-overview/benutzer-overview.component.html, bogenliga/src/app/modules/verwaltung/components/benutzer/benutzer-overview/benutzer-overview.component.ts
Task 654 Subtask 711 finished; lint aproved
=> Gruppenbranch ghost coder

bogenliga/src/app/modules/vereine/components/vereine/vereine.component.ts, bogenliga/src/app/modules/wettkampf/components/wettkampf/wettkampf.component.ts
Die ngOnInit ist jetzt nicht mehr asynchron
Backend Calls wurden ausgegliedert damit direkt verlinkt wird
=> BSAPP 460 - 623 & 631: Überarbeitung

bogenliga/src/app/modules/verwaltung/types/datatransfer/veranstaltung-dto.class.ts
… 409Error Conflict as a response from the Backend
=> Fix a Bug where it was forgotten to declare the Version, it leaded to 409Error Conflict as a Response from the Backend

bogenliga/src/app/modules/sportjahresplan/components/schusszettel/schusszettel.component.ts, bogenliga/src/app/modules/wettkampf/components/wettkampf/wettkampf.component.html, bogenliga/src/app/modules/wettkampf/components/wettkampf/wettkampf.component.ts, bogenliga/src/app/modules/wettkampf/services/wettkampf-ergebnis.service.ts
BSAPP-146, BSAPP-727, BSAPP-474
=> Gruppen branch ghost coder

bogenliga/src/app/modules/verwaltung/components/veranstaltung/veranstaltung-detail/wettkampftage/wettkampftage.component.html, bogenliga/src/app/modules/wettkampf/components/wettkampf/wettkampf.component.html, bogenliga/src/app/modules/wettkampf/components/wettkampf/wettkampf.component.ts
Changes that were made are documented in a PDF in Confluence:
https://www.exxcellent.de/confluence/display/BSAPP/2021-05-07+Meeting?preview=/121145696/122323923/BSAPP-789%20Vorschlag.pdf
Gero agreed to these changes in order to fix this small bug.
=> BSAPP-789 Bugfix implemented

bogenliga/src/assets/i18n/de.json, bogenliga/src/assets/i18n/en.json
added error Notification in json.de and .en
=> BSAPP-817 (Subtask BSAPP-905)

bogenliga/src/app/modules/verwaltung/guards/wettkampftage.guard.ts
Kurzer Fix wegen fehlender Permissions um neue Wettkampftage als Ligaleiter hinzuzufügen.
=> Permission fix

bogenliga/src/app/modules/verwaltung/components/veranstaltung/veranstaltung-detail/wettkampftage/wettkampftage.component.ts
Kurzer Fix aufgrund von Denkfehler. Eine Zeile wurde ergänzt, da die Anzahl der Wettkampftage immer anfangs auf 0 war, auch wenn schon Wettkampftage exisiterten.
=> fixed small bug

bogenliga/src/app/modules/user/components/user-pwd/user-pwd.component.html, bogenliga/src/app/modules/verwaltung/components/liga/liga-detail/liga-detail.component.ts, bogenliga/src/app/modules/verwaltung/components/user/user-detail/user-detail.component.html, bogenliga/src/app/modules/verwaltung/components/veranstaltung/veranstaltung-detail/wettkampftage/wettkampftage.component.ts, bogenliga/src/app/modules/verwaltung/components/verein/verein-detail/mannschafts-detail/mannschaft-detail.component.ts, bogenliga/src/app/modules/verwaltung/components/verein/verein-detail/mannschafts-detail/schuetzen/schuetzen.component.spec.ts, bogenliga/src/assets/i18n/de.json, bogenliga/src/assets/i18n/en.json
+ derzeitige Liga aus Auswahl der übergeordneten Liga entfernt
+ Lösch-Dialog geändert von id zu name beim Löschen Schützen
=> BSAPP-947 BSAPP-793

bogenliga/src/app/modules/user/components/user-pwd/user-pwd.component.html, bogenliga/src/app/modules/verwaltung/components/user/user-detail/user-detail.component.html, bogenliga/src/app/modules/verwaltung/components/veranstaltung/veranstaltung-detail/wettkampftage/wettkampftage.component.html, bogenliga/src/assets/i18n/de.json
Das Ticket 932 kann damit endgültig erfüllt werden (auch das ^-Zeichen wird zugelassen) 
In Wettkampftage wurde Form control etwas verbessert (um beispielsweise nur fünfstellige Postleitzahlen zuzulassen).
=> BSAPP 932 - the final merge

bogenliga/src/app/modules/verwaltung/components/veranstaltung/veranstaltung-detail/wettkampftage/wettkampftage.component.html
Button Position für "Neu" und "Kopieren" Buttons geändert. Überflüssigen Code gelöscht.
=> BSAPP - 996
